export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL'
export const AUTH_USER_PROCEEDING = 'AUTH_USER_PROCEEDING'
