export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST'
export const REGISTRATION_RESPONSE = 'REGISTRATION_RESPONSE'

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL'
export const REGISTRATION_PROCEEDING = 'REGISTRATION_PROCEEDING'
