export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCEEDED = 'ADD_TODO_SUCCEEDED'

export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST'
export const REMOVE_TODO_SUCCEEDED = 'REMOVE_TODO_SUCCEEDED'

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST'
export const GET_TODOS_SUCCEEDED = 'GET_TODOS_SUCCEEDED'

export const TODO_REQUEST_FAILED = 'TODO_REQUEST_FAILED'
export const TODO_REQUEST_PENDING = 'TODO_REQUEST_PENDING'
