export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST'
export const GET_TODOS_SUCCEEDED = 'GET_TODOS_SUCCEEDED'


export const TODO_REQUEST_FAILED = 'TODO_REQUEST_FAILED'
export const TODO_REQUEST_PENDING = 'TODO_REQUEST_PENDING'
