export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST'
export const GET_USERS_LIST_SUCCEEDED = 'GET_USERS_LIST_SUCCEEDED'
export const GET_USERS_LIST_FAILED = 'GET_USERS_LIST_FAILED'
export const GET_USERS_LIST_PROCEEDING = 'GET_USERS_LIST_PROCEEDING'

export const UPDATE_USER_ADDRESS_REQUEST = 'UPDATE_USER_ADDRESS_REQUEST'
export const UPDATE_USER_ADDRESS_SUCCEEDED = 'UPDATE_USER_ADDRESS_SUCCEEDED'

export const GET_USER_ADDRESS_REQUEST = 'GET_USER_ADDRESS_REQUEST'
export const GET_USER_ADDRESS_SUCCEEDED = 'GET_USER_ADDRESS_SUCCEEDED'
export const RESET_USER_ADDRESS = 'RESET_USER_ADDRESS'