export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST'
export const GET_USERS_LIST_SUCCEEDED = 'GET_USERS_LIST_SUCCEEDED'
export const GET_USERS_LIST_FAILED = 'GET_USERS_LIST_FAILED'
export const GET_USERS_LIST_PROCEEDING = 'GET_USERS_LIST'
