export const GET_FRIENDS_REQUEST = 'GET_FRIENDS_REQUEST'
export const FRIENDS_FETCH_SUCCEEDED = 'FRIENDS_FETCH_SUCCEEDED'
export const FRIENDS_FETCH_FAILED = 'FRIENDS_FETCH_FAILED'
export const FETCHING_FRIENDS = 'FETCHING_FRIENDS'
